In [15]:
import numpy as np

def InputMatrix(): #Takes Matrix input from the user.
    r = int(input('Enter number of rows:'))
    c = int(input('Enter number of columns:'))

    ipMat = []
    for i in range(r):
        row=[]
        for j in range(c):
            print("Enter the value in",'[',i+1,']','[',j+1,']',end=":")
            row.append(int(input()))
        ipMat.append(row)
    
    return np.array(ipMat,dtype = float)

def nullcheck(ipmat): # Check wheather the Matrix is a valid matrix or a null.
    
    ct =0
    for c in range(len(ipmat[0])):
            for r in range(len(ipmat)):
                if ipmat[r,c]==0:
                    ct +=1
    mul = len(ipmat)* len(ipmat[0])
    if ct==mul:
        print('It\'s a null matrix')

    return 

def rearr(ipmat): # Rearranges the Matrix by performing row interchange operation.
    
    if ipmat[0,0] == 0:
        for c in range(len(ipmat[0])):
            for r in range(len(ipmat)):
                if ipmat[r,c] != 0:
                    ipmat[0],ipmat[r] = ipmat[r].copy(),ipmat[0].copy()
                    break
    return ipmat

def rowtran(ipmat): # Performs Row Transformation by subtraction.   
   
    if ipmat[0,0] == 0:
        return ipmat
    for j in range(1,len(ipmat)):
        ipmat[j] = ipmat[j]-ipmat[j,0]/ipmat[0,0] * ipmat[0]
    
    return ipmat
    

def rowech(ipmat): # Insert all the Minors in the main Matrix. 
    
    rec = min(len(ipmat),len(ipmat[0]))
    for h in range(rec):
        ipmat[h:,h:] = rearr(ipmat[h:,h:])
        counter = 0
        for c in range(h,len(ipmat[0])):
            if ipmat[h,c] ==0:
                counter +=1
        if h+counter>=len(ipmat[0]):
            continue
        ipmat[h:,h+counter:] = rowtran(ipmat[h:,h+counter:])
        
    return ipmat


def rankfind (ipmat): # Finds the rank of the Matrix.
    
    rank = 0
    for r in range(len(ipmat)):
        for c in range(len(ipmat[0])):
            if ipmat[r,c] != 0:
                rank += 1
                break
                
    return rank 

def rowEchTran (): # Calls all the Functions.
    
    ipmat = InputMatrix()
    print("Input Matrix is:\n",ipmat)
    cp = nullcheck(ipmat)
    rowech(ipmat)    
    print("Row Echelon form is:\n",ipmat)    
    rank = rankfind(ipmat)
    print ('Rank of the Matrix:',rank)
    
    return

rowEchTran()


Enter number of rows:3
Enter number of columns:3
Enter the value in [ 1 ] [ 1 ]:1
Enter the value in [ 1 ] [ 2 ]:2
Enter the value in [ 1 ] [ 3 ]:3
Enter the value in [ 2 ] [ 1 ]:4
Enter the value in [ 2 ] [ 2 ]:5
Enter the value in [ 2 ] [ 3 ]:6
Enter the value in [ 3 ] [ 1 ]:7
Enter the value in [ 3 ] [ 2 ]:8
Enter the value in [ 3 ] [ 3 ]:9
Input Matrix is:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Row Echelon form is:
 [[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  0.]]
Rank of the Matrix: 2
